//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_clock_H
#define METASPRITE_bg_clock_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_clock_TILE_ORIGIN 0
#define bg_clock_TILE_W 8
#define bg_clock_TILE_H 8
#define bg_clock_WIDTH 168
#define bg_clock_HEIGHT 160
#define bg_clock_TILE_COUNT 83
#define bg_clock_PALETTE_COUNT 1
#define bg_clock_COLORS_PER_PALETTE 4
#define bg_clock_TOTAL_COLORS 4
#define bg_clock_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bg_clock)

extern const palette_color_t bg_clock_palettes[4];
extern const uint8_t bg_clock_tiles[1328];

extern const unsigned char bg_clock_map[420];

#endif
