//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_field_H
#define METASPRITE_bg_field_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_field_TILE_ORIGIN 0
#define bg_field_TILE_W 8
#define bg_field_TILE_H 8
#define bg_field_WIDTH 160
#define bg_field_HEIGHT 144
#define bg_field_TILE_COUNT 87
#define bg_field_PALETTE_COUNT 1
#define bg_field_COLORS_PER_PALETTE 4
#define bg_field_TOTAL_COLORS 4
#define bg_field_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bg_field)

extern const palette_color_t bg_field_palettes[4];
extern const uint8_t bg_field_tiles[1392];

extern const unsigned char bg_field_map[360];

#endif
