//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_field_night_H
#define METASPRITE_bg_field_night_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_field_night_TILE_ORIGIN 0
#define bg_field_night_TILE_W 8
#define bg_field_night_TILE_H 8
#define bg_field_night_WIDTH 160
#define bg_field_night_HEIGHT 144
#define bg_field_night_TILE_COUNT 100
#define bg_field_night_PALETTE_COUNT 1
#define bg_field_night_COLORS_PER_PALETTE 4
#define bg_field_night_TOTAL_COLORS 4
#define bg_field_night_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bg_field_night)

extern const palette_color_t bg_field_night_palettes[4];
extern const uint8_t bg_field_night_tiles[1600];

extern const unsigned char bg_field_night_map[360];

#endif
