//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_main_H
#define METASPRITE_bg_main_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_main_TILE_ORIGIN 0
#define bg_main_TILE_W 8
#define bg_main_TILE_H 8
#define bg_main_WIDTH 160
#define bg_main_HEIGHT 176
#define bg_main_TILE_COUNT 159
#define bg_main_PALETTE_COUNT 1
#define bg_main_COLORS_PER_PALETTE 4
#define bg_main_TOTAL_COLORS 4
#define bg_main_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bg_main)

extern const palette_color_t bg_main_palettes[4];
extern const uint8_t bg_main_tiles[2544];

extern const unsigned char bg_main_map[440];

#endif
