//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_stats_H
#define METASPRITE_bg_stats_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_stats_TILE_ORIGIN 0
#define bg_stats_TILE_W 8
#define bg_stats_TILE_H 8
#define bg_stats_WIDTH 160
#define bg_stats_HEIGHT 144
#define bg_stats_TILE_COUNT 71
#define bg_stats_PALETTE_COUNT 1
#define bg_stats_COLORS_PER_PALETTE 4
#define bg_stats_TOTAL_COLORS 4
#define bg_stats_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bg_stats)

extern const palette_color_t bg_stats_palettes[4];
extern const uint8_t bg_stats_tiles[1136];

extern const unsigned char bg_stats_map[360];

#endif
