#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fruit_count_2)

const palette_color_t fruit_count_2_palettes[4] = {
	RGB8(226,223,177), RGB8(176,184,127), RGB8(115,130, 92), RGB8( 68, 68, 41)
	
};

const uint8_t fruit_count_2_tiles[16] = {
	0xb5,0xde,0x42,0xb9,
	0xfd,0xfd,0xa6,0xa9,
	0x5a,0xd3,0xf7,0xa9,
	0xdf,0xff,0x81,0x7e
	};


const unsigned char fruit_count_2_map[1] = {
	0x00,
};
