//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fruit_count_5_H
#define METASPRITE_fruit_count_5_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fruit_count_5_TILE_ORIGIN 0
#define fruit_count_5_TILE_W 8
#define fruit_count_5_TILE_H 8
#define fruit_count_5_WIDTH 8
#define fruit_count_5_HEIGHT 8
#define fruit_count_5_TILE_COUNT 1
#define fruit_count_5_PALETTE_COUNT 1
#define fruit_count_5_COLORS_PER_PALETTE 4
#define fruit_count_5_TOTAL_COLORS 4
#define fruit_count_5_MAP_ATTRIBUTES 0

BANKREF_EXTERN(fruit_count_5)

extern const palette_color_t fruit_count_5_palettes[4];
extern const uint8_t fruit_count_5_tiles[16];

extern const unsigned char fruit_count_5_map[1];

#endif
