#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fruit_count_3)

const palette_color_t fruit_count_3_palettes[4] = {
	RGB8(226,223,177), RGB8(176,184,127), RGB8(115,130, 92), RGB8( 68, 68, 41)
	
};

const uint8_t fruit_count_3_tiles[16] = {
	0xa9,0xde,0x58,0xb3,
	0xf9,0xfd,0xa2,0xab,
	0x59,0xdd,0xfa,0xa1,
	0xdc,0xff,0x81,0x7e
	};


const unsigned char fruit_count_3_map[1] = {
	0x00,
};
