//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fruit_count_6_H
#define METASPRITE_fruit_count_6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fruit_count_6_TILE_ORIGIN 0
#define fruit_count_6_TILE_W 8
#define fruit_count_6_TILE_H 8
#define fruit_count_6_WIDTH 8
#define fruit_count_6_HEIGHT 8
#define fruit_count_6_TILE_COUNT 1
#define fruit_count_6_PALETTE_COUNT 1
#define fruit_count_6_COLORS_PER_PALETTE 4
#define fruit_count_6_TOTAL_COLORS 4
#define fruit_count_6_MAP_ATTRIBUTES 0

BANKREF_EXTERN(fruit_count_6)

extern const palette_color_t fruit_count_6_palettes[4];
extern const uint8_t fruit_count_6_tiles[16];

extern const unsigned char fruit_count_6_map[1];

#endif
