//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fruit_count_3_H
#define METASPRITE_fruit_count_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fruit_count_3_TILE_ORIGIN 0
#define fruit_count_3_TILE_W 8
#define fruit_count_3_TILE_H 8
#define fruit_count_3_WIDTH 8
#define fruit_count_3_HEIGHT 8
#define fruit_count_3_TILE_COUNT 1
#define fruit_count_3_PALETTE_COUNT 1
#define fruit_count_3_COLORS_PER_PALETTE 4
#define fruit_count_3_TOTAL_COLORS 4
#define fruit_count_3_MAP_ATTRIBUTES 0

BANKREF_EXTERN(fruit_count_3)

extern const palette_color_t fruit_count_3_palettes[4];
extern const uint8_t fruit_count_3_tiles[16];

extern const unsigned char fruit_count_3_map[1];

#endif
