#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fruit_count_6)

const palette_color_t fruit_count_6_palettes[4] = {
	RGB8(226,223,177), RGB8(176,184,127), RGB8(115,130, 92), RGB8( 68, 68, 41)
	
};

const uint8_t fruit_count_6_tiles[16] = {
	0xb0,0xdf,0x49,0xbd,
	0xf2,0xfb,0xae,0xb1,
	0x55,0xd5,0xf5,0xab,
	0xde,0xff,0x81,0x7e
	};


const unsigned char fruit_count_6_map[1] = {
	0x00,
};
