#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fruit_count_1)

const palette_color_t fruit_count_1_palettes[4] = {
	RGB8(226,223,177), RGB8(176,184,127), RGB8(115,130, 92), RGB8( 68, 68, 41)
	
};

const uint8_t fruit_count_1_tiles[16] = {
	0xbf,0xd8,0x57,0xb8,
	0xbf,0x70,0xef,0xf0,
	0xbf,0xc0,0xff,0x00,
	0xff,0x00,0xff,0x00
	};


const unsigned char fruit_count_1_map[1] = {
	0x00,
};
