#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fruit_count_5)

const palette_color_t fruit_count_5_palettes[4] = {
	RGB8(226,223,177), RGB8(176,184,127), RGB8(115,130, 92), RGB8( 68, 68, 41)
	
};

const uint8_t fruit_count_5_tiles[16] = {
	0xb8,0xd7,0x50,0xb9,
	0xfb,0xfb,0xa7,0xa8,
	0x5c,0xdd,0xf3,0xa9,
	0xde,0xff,0x81,0x7e
	};


const unsigned char fruit_count_5_map[1] = {
	0x00,
};
