#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fruit_count_4)

const palette_color_t fruit_count_4_palettes[4] = {
	RGB8(226,223,177), RGB8(176,184,127), RGB8(115,130, 92), RGB8( 68, 68, 41)
	
};

const uint8_t fruit_count_4_tiles[16] = {
	0xbd,0xd6,0x4a,0xbb,
	0xff,0xf5,0xa0,0xb1,
	0x5e,0xdd,0xf7,0xad,
	0xdf,0xff,0x81,0x7e
	};


const unsigned char fruit_count_4_map[1] = {
	0x00,
};
