//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_fruit_blueberry_H
#define METASPRITE_menu_fruit_blueberry_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_fruit_blueberry_TILE_ORIGIN 0
#define menu_fruit_blueberry_TILE_W 8
#define menu_fruit_blueberry_TILE_H 8
#define menu_fruit_blueberry_WIDTH 16
#define menu_fruit_blueberry_HEIGHT 16
#define menu_fruit_blueberry_TILE_COUNT 4
#define menu_fruit_blueberry_PALETTE_COUNT 1
#define menu_fruit_blueberry_COLORS_PER_PALETTE 4
#define menu_fruit_blueberry_TOTAL_COLORS 4
#define menu_fruit_blueberry_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_fruit_blueberry)

extern const palette_color_t menu_fruit_blueberry_palettes[4];
extern const uint8_t menu_fruit_blueberry_tiles[64];

extern const unsigned char menu_fruit_blueberry_map[4];

#endif
