//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_soap_H
#define METASPRITE_menu_soap_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_soap_TILE_ORIGIN 0
#define menu_soap_TILE_W 8
#define menu_soap_TILE_H 8
#define menu_soap_WIDTH 16
#define menu_soap_HEIGHT 16
#define menu_soap_TILE_COUNT 4
#define menu_soap_PALETTE_COUNT 1
#define menu_soap_COLORS_PER_PALETTE 4
#define menu_soap_TOTAL_COLORS 4
#define menu_soap_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_soap)

extern const palette_color_t menu_soap_palettes[4];
extern const uint8_t menu_soap_tiles[64];

extern const unsigned char menu_soap_map[4];

#endif
