//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_moon_H
#define METASPRITE_menu_moon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_moon_TILE_ORIGIN 0
#define menu_moon_TILE_W 8
#define menu_moon_TILE_H 8
#define menu_moon_WIDTH 16
#define menu_moon_HEIGHT 16
#define menu_moon_TILE_COUNT 4
#define menu_moon_PALETTE_COUNT 1
#define menu_moon_COLORS_PER_PALETTE 4
#define menu_moon_TOTAL_COLORS 4
#define menu_moon_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_moon)

extern const palette_color_t menu_moon_palettes[4];
extern const uint8_t menu_moon_tiles[64];

extern const unsigned char menu_moon_map[4];

#endif
