//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_stats_H
#define METASPRITE_menu_stats_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_stats_TILE_ORIGIN 0
#define menu_stats_TILE_W 8
#define menu_stats_TILE_H 8
#define menu_stats_WIDTH 16
#define menu_stats_HEIGHT 16
#define menu_stats_TILE_COUNT 4
#define menu_stats_PALETTE_COUNT 1
#define menu_stats_COLORS_PER_PALETTE 4
#define menu_stats_TOTAL_COLORS 4
#define menu_stats_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_stats)

extern const palette_color_t menu_stats_palettes[4];
extern const uint8_t menu_stats_tiles[64];

extern const unsigned char menu_stats_map[4];

#endif
