//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_jar_full_H
#define METASPRITE_menu_jar_full_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_jar_full_TILE_ORIGIN 0
#define menu_jar_full_TILE_W 8
#define menu_jar_full_TILE_H 8
#define menu_jar_full_WIDTH 16
#define menu_jar_full_HEIGHT 16
#define menu_jar_full_TILE_COUNT 4
#define menu_jar_full_PALETTE_COUNT 1
#define menu_jar_full_COLORS_PER_PALETTE 4
#define menu_jar_full_TOTAL_COLORS 4
#define menu_jar_full_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_jar_full)

extern const palette_color_t menu_jar_full_palettes[4];
extern const uint8_t menu_jar_full_tiles[64];

extern const unsigned char menu_jar_full_map[4];

#endif
