//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_jar_empty_H
#define METASPRITE_menu_jar_empty_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_jar_empty_TILE_ORIGIN 0
#define menu_jar_empty_TILE_W 8
#define menu_jar_empty_TILE_H 8
#define menu_jar_empty_WIDTH 16
#define menu_jar_empty_HEIGHT 16
#define menu_jar_empty_TILE_COUNT 4
#define menu_jar_empty_PALETTE_COUNT 1
#define menu_jar_empty_COLORS_PER_PALETTE 4
#define menu_jar_empty_TOTAL_COLORS 4
#define menu_jar_empty_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_jar_empty)

extern const palette_color_t menu_jar_empty_palettes[4];
extern const uint8_t menu_jar_empty_tiles[64];

extern const unsigned char menu_jar_empty_map[4];

#endif
