//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_moon_outline_H
#define METASPRITE_menu_moon_outline_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_moon_outline_TILE_ORIGIN 0
#define menu_moon_outline_TILE_W 8
#define menu_moon_outline_TILE_H 8
#define menu_moon_outline_WIDTH 16
#define menu_moon_outline_HEIGHT 16
#define menu_moon_outline_TILE_COUNT 4
#define menu_moon_outline_PALETTE_COUNT 1
#define menu_moon_outline_COLORS_PER_PALETTE 4
#define menu_moon_outline_TOTAL_COLORS 4
#define menu_moon_outline_MAP_ATTRIBUTES 0

BANKREF_EXTERN(menu_moon_outline)

extern const palette_color_t menu_moon_outline_palettes[4];
extern const uint8_t menu_moon_outline_tiles[64];

extern const unsigned char menu_moon_outline_map[4];

#endif
