//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_plant_H
#define METASPRITE_plant_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define plant_TILE_ORIGIN 0
#define plant_TILE_W 8
#define plant_TILE_H 8
#define plant_WIDTH 176
#define plant_HEIGHT 8
#define plant_TILE_COUNT 22
#define plant_PALETTE_COUNT 1
#define plant_COLORS_PER_PALETTE 4
#define plant_TOTAL_COLORS 4
#define plant_MAP_ATTRIBUTES 0

BANKREF_EXTERN(plant)

extern const palette_color_t plant_palettes[4];
extern const uint8_t plant_tiles[352];

extern const unsigned char plant_map[22];

#endif
