//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pond_sparkle_H
#define METASPRITE_pond_sparkle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pond_sparkle_TILE_ORIGIN 0
#define pond_sparkle_TILE_W 8
#define pond_sparkle_TILE_H 8
#define pond_sparkle_WIDTH 48
#define pond_sparkle_HEIGHT 8
#define pond_sparkle_TILE_COUNT 6
#define pond_sparkle_PALETTE_COUNT 1
#define pond_sparkle_COLORS_PER_PALETTE 4
#define pond_sparkle_TOTAL_COLORS 4
#define pond_sparkle_MAP_ATTRIBUTES 0

BANKREF_EXTERN(pond_sparkle)

extern const palette_color_t pond_sparkle_palettes[4];
extern const uint8_t pond_sparkle_tiles[96];

extern const unsigned char pond_sparkle_map[6];

#endif
