//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_speed_pause_H
#define METASPRITE_speed_pause_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define speed_pause_TILE_ORIGIN 0
#define speed_pause_TILE_W 8
#define speed_pause_TILE_H 8
#define speed_pause_WIDTH 24
#define speed_pause_HEIGHT 16
#define speed_pause_TILE_COUNT 6
#define speed_pause_PALETTE_COUNT 1
#define speed_pause_COLORS_PER_PALETTE 4
#define speed_pause_TOTAL_COLORS 4
#define speed_pause_MAP_ATTRIBUTES 0

BANKREF_EXTERN(speed_pause)

extern const palette_color_t speed_pause_palettes[4];
extern const uint8_t speed_pause_tiles[96];

extern const unsigned char speed_pause_map[6];

#endif
