//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_speed_slow_H
#define METASPRITE_speed_slow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define speed_slow_TILE_ORIGIN 0
#define speed_slow_TILE_W 8
#define speed_slow_TILE_H 8
#define speed_slow_WIDTH 24
#define speed_slow_HEIGHT 16
#define speed_slow_TILE_COUNT 6
#define speed_slow_PALETTE_COUNT 1
#define speed_slow_COLORS_PER_PALETTE 4
#define speed_slow_TOTAL_COLORS 4
#define speed_slow_MAP_ATTRIBUTES 0

BANKREF_EXTERN(speed_slow)

extern const palette_color_t speed_slow_palettes[4];
extern const uint8_t speed_slow_tiles[96];

extern const unsigned char speed_slow_map[6];

#endif
