//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_speed_fast_H
#define METASPRITE_speed_fast_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define speed_fast_TILE_ORIGIN 0
#define speed_fast_TILE_W 8
#define speed_fast_TILE_H 8
#define speed_fast_WIDTH 24
#define speed_fast_HEIGHT 16
#define speed_fast_TILE_COUNT 6
#define speed_fast_PALETTE_COUNT 1
#define speed_fast_COLORS_PER_PALETTE 4
#define speed_fast_TOTAL_COLORS 4
#define speed_fast_MAP_ATTRIBUTES 0

BANKREF_EXTERN(speed_fast)

extern const palette_color_t speed_fast_palettes[4];
extern const uint8_t speed_fast_tiles[96];

extern const unsigned char speed_fast_map[6];

#endif
