//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_speed_normal_H
#define METASPRITE_speed_normal_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define speed_normal_TILE_ORIGIN 0
#define speed_normal_TILE_W 8
#define speed_normal_TILE_H 8
#define speed_normal_WIDTH 24
#define speed_normal_HEIGHT 16
#define speed_normal_TILE_COUNT 6
#define speed_normal_PALETTE_COUNT 1
#define speed_normal_COLORS_PER_PALETTE 4
#define speed_normal_TOTAL_COLORS 4
#define speed_normal_MAP_ATTRIBUTES 0

BANKREF_EXTERN(speed_normal)

extern const palette_color_t speed_normal_palettes[4];
extern const uint8_t speed_normal_tiles[96];

extern const unsigned char speed_normal_map[6];

#endif
