//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_title_screen_H
#define METASPRITE_title_screen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define title_screen_TILE_ORIGIN 0
#define title_screen_TILE_W 8
#define title_screen_TILE_H 8
#define title_screen_WIDTH 160
#define title_screen_HEIGHT 144
#define title_screen_TILE_COUNT 90
#define title_screen_PALETTE_COUNT 1
#define title_screen_COLORS_PER_PALETTE 4
#define title_screen_TOTAL_COLORS 4
#define title_screen_MAP_ATTRIBUTES 0

BANKREF_EXTERN(title_screen)

extern const palette_color_t title_screen_palettes[4];
extern const uint8_t title_screen_tiles[1440];

extern const unsigned char title_screen_map[360];

#endif
