//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fruit_blueberry_3_H
#define METASPRITE_fruit_blueberry_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fruit_blueberry_3_TILE_ORIGIN 0
#define fruit_blueberry_3_TILE_W 8
#define fruit_blueberry_3_TILE_H 8
#define fruit_blueberry_3_WIDTH 24
#define fruit_blueberry_3_HEIGHT 16
#define fruit_blueberry_3_TILE_COUNT 19
#define fruit_blueberry_3_PALETTE_COUNT 1
#define fruit_blueberry_3_COLORS_PER_PALETTE 4
#define fruit_blueberry_3_TOTAL_COLORS 4
#define fruit_blueberry_3_PIVOT_X 12
#define fruit_blueberry_3_PIVOT_Y 8
#define fruit_blueberry_3_PIVOT_W 24
#define fruit_blueberry_3_PIVOT_H 16

BANKREF_EXTERN(fruit_blueberry_3)

extern const palette_color_t fruit_blueberry_3_palettes[4];
extern const uint8_t fruit_blueberry_3_tiles[304];

extern const metasprite_t* const fruit_blueberry_3_metasprites[8];

#endif
