//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fruit_strawberry_2_H
#define METASPRITE_fruit_strawberry_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fruit_strawberry_2_TILE_ORIGIN 0
#define fruit_strawberry_2_TILE_W 8
#define fruit_strawberry_2_TILE_H 8
#define fruit_strawberry_2_WIDTH 24
#define fruit_strawberry_2_HEIGHT 16
#define fruit_strawberry_2_TILE_COUNT 30
#define fruit_strawberry_2_PALETTE_COUNT 1
#define fruit_strawberry_2_COLORS_PER_PALETTE 4
#define fruit_strawberry_2_TOTAL_COLORS 4
#define fruit_strawberry_2_PIVOT_X 12
#define fruit_strawberry_2_PIVOT_Y 8
#define fruit_strawberry_2_PIVOT_W 24
#define fruit_strawberry_2_PIVOT_H 16

BANKREF_EXTERN(fruit_strawberry_2)

extern const palette_color_t fruit_strawberry_2_palettes[4];
extern const uint8_t fruit_strawberry_2_tiles[480];

extern const metasprite_t* const fruit_strawberry_2_metasprites[8];

#endif
