//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fruit_blackberry_1_H
#define METASPRITE_fruit_blackberry_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fruit_blackberry_1_TILE_ORIGIN 0
#define fruit_blackberry_1_TILE_W 8
#define fruit_blackberry_1_TILE_H 8
#define fruit_blackberry_1_WIDTH 24
#define fruit_blackberry_1_HEIGHT 16
#define fruit_blackberry_1_TILE_COUNT 38
#define fruit_blackberry_1_PALETTE_COUNT 1
#define fruit_blackberry_1_COLORS_PER_PALETTE 4
#define fruit_blackberry_1_TOTAL_COLORS 4
#define fruit_blackberry_1_PIVOT_X 12
#define fruit_blackberry_1_PIVOT_Y 8
#define fruit_blackberry_1_PIVOT_W 24
#define fruit_blackberry_1_PIVOT_H 16

BANKREF_EXTERN(fruit_blackberry_1)

extern const palette_color_t fruit_blackberry_1_palettes[4];
extern const uint8_t fruit_blackberry_1_tiles[608];

extern const metasprite_t* const fruit_blackberry_1_metasprites[8];

#endif
