//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_tickle_1_H
#define METASPRITE_hand_tickle_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_tickle_1_TILE_ORIGIN 0
#define hand_tickle_1_TILE_W 8
#define hand_tickle_1_TILE_H 8
#define hand_tickle_1_WIDTH 24
#define hand_tickle_1_HEIGHT 16
#define hand_tickle_1_TILE_COUNT 41
#define hand_tickle_1_PALETTE_COUNT 1
#define hand_tickle_1_COLORS_PER_PALETTE 4
#define hand_tickle_1_TOTAL_COLORS 4
#define hand_tickle_1_PIVOT_X 12
#define hand_tickle_1_PIVOT_Y 8
#define hand_tickle_1_PIVOT_W 24
#define hand_tickle_1_PIVOT_H 16

BANKREF_EXTERN(hand_tickle_1)

extern const palette_color_t hand_tickle_1_palettes[4];
extern const uint8_t hand_tickle_1_tiles[656];

extern const metasprite_t* const hand_tickle_1_metasprites[8];

#endif
