//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_moon_H
#define METASPRITE_hand_moon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_moon_TILE_ORIGIN 0
#define hand_moon_TILE_W 8
#define hand_moon_TILE_H 8
#define hand_moon_WIDTH 24
#define hand_moon_HEIGHT 16
#define hand_moon_TILE_COUNT 43
#define hand_moon_PALETTE_COUNT 1
#define hand_moon_COLORS_PER_PALETTE 4
#define hand_moon_TOTAL_COLORS 4
#define hand_moon_PIVOT_X 12
#define hand_moon_PIVOT_Y 8
#define hand_moon_PIVOT_W 24
#define hand_moon_PIVOT_H 16

BANKREF_EXTERN(hand_moon)

extern const palette_color_t hand_moon_palettes[4];
extern const uint8_t hand_moon_tiles[688];

extern const metasprite_t* const hand_moon_metasprites[8];

#endif
