//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_jar_1_3_H
#define METASPRITE_hand_jar_1_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_jar_1_3_TILE_ORIGIN 0
#define hand_jar_1_3_TILE_W 8
#define hand_jar_1_3_TILE_H 8
#define hand_jar_1_3_WIDTH 24
#define hand_jar_1_3_HEIGHT 16
#define hand_jar_1_3_TILE_COUNT 42
#define hand_jar_1_3_PALETTE_COUNT 1
#define hand_jar_1_3_COLORS_PER_PALETTE 4
#define hand_jar_1_3_TOTAL_COLORS 4
#define hand_jar_1_3_PIVOT_X 12
#define hand_jar_1_3_PIVOT_Y 8
#define hand_jar_1_3_PIVOT_W 24
#define hand_jar_1_3_PIVOT_H 16

BANKREF_EXTERN(hand_jar_1_3)

extern const palette_color_t hand_jar_1_3_palettes[4];
extern const uint8_t hand_jar_1_3_tiles[672];

extern const metasprite_t* const hand_jar_1_3_metasprites[8];

#endif
