//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_tickle_2_H
#define METASPRITE_hand_tickle_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_tickle_2_TILE_ORIGIN 0
#define hand_tickle_2_TILE_W 8
#define hand_tickle_2_TILE_H 8
#define hand_tickle_2_WIDTH 24
#define hand_tickle_2_HEIGHT 16
#define hand_tickle_2_TILE_COUNT 41
#define hand_tickle_2_PALETTE_COUNT 1
#define hand_tickle_2_COLORS_PER_PALETTE 4
#define hand_tickle_2_TOTAL_COLORS 4
#define hand_tickle_2_PIVOT_X 12
#define hand_tickle_2_PIVOT_Y 8
#define hand_tickle_2_PIVOT_W 24
#define hand_tickle_2_PIVOT_H 16

BANKREF_EXTERN(hand_tickle_2)

extern const palette_color_t hand_tickle_2_palettes[4];
extern const uint8_t hand_tickle_2_tiles[656];

extern const metasprite_t* const hand_tickle_2_metasprites[8];

#endif
