//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_jar_empty_H
#define METASPRITE_hand_jar_empty_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_jar_empty_TILE_ORIGIN 0
#define hand_jar_empty_TILE_W 8
#define hand_jar_empty_TILE_H 8
#define hand_jar_empty_WIDTH 24
#define hand_jar_empty_HEIGHT 16
#define hand_jar_empty_TILE_COUNT 42
#define hand_jar_empty_PALETTE_COUNT 1
#define hand_jar_empty_COLORS_PER_PALETTE 4
#define hand_jar_empty_TOTAL_COLORS 4
#define hand_jar_empty_PIVOT_X 12
#define hand_jar_empty_PIVOT_Y 8
#define hand_jar_empty_PIVOT_W 24
#define hand_jar_empty_PIVOT_H 16

BANKREF_EXTERN(hand_jar_empty)

extern const palette_color_t hand_jar_empty_palettes[4];
extern const uint8_t hand_jar_empty_tiles[672];

extern const metasprite_t* const hand_jar_empty_metasprites[8];

#endif
