//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_blueberry_H
#define METASPRITE_hand_blueberry_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_blueberry_TILE_ORIGIN 0
#define hand_blueberry_TILE_W 8
#define hand_blueberry_TILE_H 8
#define hand_blueberry_WIDTH 24
#define hand_blueberry_HEIGHT 16
#define hand_blueberry_TILE_COUNT 45
#define hand_blueberry_PALETTE_COUNT 1
#define hand_blueberry_COLORS_PER_PALETTE 4
#define hand_blueberry_TOTAL_COLORS 4
#define hand_blueberry_PIVOT_X 12
#define hand_blueberry_PIVOT_Y 8
#define hand_blueberry_PIVOT_W 24
#define hand_blueberry_PIVOT_H 16

BANKREF_EXTERN(hand_blueberry)

extern const palette_color_t hand_blueberry_palettes[4];
extern const uint8_t hand_blueberry_tiles[720];

extern const metasprite_t* const hand_blueberry_metasprites[8];

#endif
