//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hand_fly_H
#define METASPRITE_hand_fly_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hand_fly_TILE_ORIGIN 0
#define hand_fly_TILE_W 8
#define hand_fly_TILE_H 8
#define hand_fly_WIDTH 24
#define hand_fly_HEIGHT 16
#define hand_fly_TILE_COUNT 46
#define hand_fly_PALETTE_COUNT 1
#define hand_fly_COLORS_PER_PALETTE 4
#define hand_fly_TOTAL_COLORS 4
#define hand_fly_PIVOT_X 12
#define hand_fly_PIVOT_Y 8
#define hand_fly_PIVOT_W 24
#define hand_fly_PIVOT_H 16

BANKREF_EXTERN(hand_fly)

extern const palette_color_t hand_fly_palettes[4];
extern const uint8_t hand_fly_tiles[736];

extern const metasprite_t* const hand_fly_metasprites[8];

#endif
