//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_teen_apple_walk_right_H
#define METASPRITE_frog_teen_apple_walk_right_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_teen_apple_walk_right_TILE_ORIGIN 0
#define frog_teen_apple_walk_right_TILE_W 8
#define frog_teen_apple_walk_right_TILE_H 8
#define frog_teen_apple_walk_right_WIDTH 32
#define frog_teen_apple_walk_right_HEIGHT 32
#define frog_teen_apple_walk_right_TILE_COUNT 20
#define frog_teen_apple_walk_right_PALETTE_COUNT 1
#define frog_teen_apple_walk_right_COLORS_PER_PALETTE 4
#define frog_teen_apple_walk_right_TOTAL_COLORS 4
#define frog_teen_apple_walk_right_PIVOT_X 16
#define frog_teen_apple_walk_right_PIVOT_Y 16
#define frog_teen_apple_walk_right_PIVOT_W 32
#define frog_teen_apple_walk_right_PIVOT_H 32

BANKREF_EXTERN(frog_teen_apple_walk_right)

extern const palette_color_t frog_teen_apple_walk_right_palettes[4];
extern const uint8_t frog_teen_apple_walk_right_tiles[320];

extern const metasprite_t* const frog_teen_apple_walk_right_metasprites[2];

#endif
