//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_teen_apple_sleep_H
#define METASPRITE_frog_teen_apple_sleep_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_teen_apple_sleep_TILE_ORIGIN 0
#define frog_teen_apple_sleep_TILE_W 8
#define frog_teen_apple_sleep_TILE_H 8
#define frog_teen_apple_sleep_WIDTH 32
#define frog_teen_apple_sleep_HEIGHT 32
#define frog_teen_apple_sleep_TILE_COUNT 10
#define frog_teen_apple_sleep_PALETTE_COUNT 1
#define frog_teen_apple_sleep_COLORS_PER_PALETTE 4
#define frog_teen_apple_sleep_TOTAL_COLORS 4
#define frog_teen_apple_sleep_PIVOT_X 16
#define frog_teen_apple_sleep_PIVOT_Y 16
#define frog_teen_apple_sleep_PIVOT_W 32
#define frog_teen_apple_sleep_PIVOT_H 32

BANKREF_EXTERN(frog_teen_apple_sleep)

extern const palette_color_t frog_teen_apple_sleep_palettes[4];
extern const uint8_t frog_teen_apple_sleep_tiles[160];

extern const metasprite_t* const frog_teen_apple_sleep_metasprites[2];

#endif
