//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_child_eat_H
#define METASPRITE_frog_child_eat_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_child_eat_TILE_ORIGIN 0
#define frog_child_eat_TILE_W 8
#define frog_child_eat_TILE_H 8
#define frog_child_eat_WIDTH 32
#define frog_child_eat_HEIGHT 32
#define frog_child_eat_TILE_COUNT 8
#define frog_child_eat_PALETTE_COUNT 1
#define frog_child_eat_COLORS_PER_PALETTE 4
#define frog_child_eat_TOTAL_COLORS 4
#define frog_child_eat_PIVOT_X 16
#define frog_child_eat_PIVOT_Y 16
#define frog_child_eat_PIVOT_W 32
#define frog_child_eat_PIVOT_H 32

BANKREF_EXTERN(frog_child_eat)

extern const palette_color_t frog_child_eat_palettes[4];
extern const uint8_t frog_child_eat_tiles[128];

extern const metasprite_t* const frog_child_eat_metasprites[2];

#endif
