//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_moon_H
#define METASPRITE_moon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define moon_TILE_ORIGIN 0
#define moon_TILE_W 8
#define moon_TILE_H 8
#define moon_WIDTH 16
#define moon_HEIGHT 16
#define moon_TILE_COUNT 15
#define moon_PALETTE_COUNT 1
#define moon_COLORS_PER_PALETTE 4
#define moon_TOTAL_COLORS 4
#define moon_PIVOT_X 8
#define moon_PIVOT_Y 8
#define moon_PIVOT_W 16
#define moon_PIVOT_H 16

BANKREF_EXTERN(moon)

extern const palette_color_t moon_palettes[4];
extern const uint8_t moon_tiles[240];

extern const metasprite_t* const moon_metasprites[5];

#endif
