#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(arrow)

const palette_color_t arrow_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8( 68, 68, 41), RGB8( 84,127,  0)
	
};

const uint8_t arrow_tiles[16] = {
	0x00,0x18,0x10,0x2c,
	0x20,0x5e,0x00,0xff,
	0x00,0xff,0x00,0x3c,
	0x00,0x3c,0x00,0x3c
	
};

const metasprite_t arrow_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

const metasprite_t* const arrow_metasprites[1] = {
	arrow_metasprite0
};
