//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_arrow_H
#define METASPRITE_arrow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define arrow_TILE_ORIGIN 0
#define arrow_TILE_W 8
#define arrow_TILE_H 8
#define arrow_WIDTH 8
#define arrow_HEIGHT 8
#define arrow_TILE_COUNT 1
#define arrow_PALETTE_COUNT 1
#define arrow_COLORS_PER_PALETTE 4
#define arrow_TOTAL_COLORS 4
#define arrow_PIVOT_X 4
#define arrow_PIVOT_Y 4
#define arrow_PIVOT_W 8
#define arrow_PIVOT_H 8

BANKREF_EXTERN(arrow)

extern const palette_color_t arrow_palettes[4];
extern const uint8_t arrow_tiles[16];

extern const metasprite_t* const arrow_metasprites[1];

#endif
