//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_adult_walk_left_H
#define METASPRITE_frog_adult_walk_left_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_adult_walk_left_TILE_ORIGIN 0
#define frog_adult_walk_left_TILE_W 8
#define frog_adult_walk_left_TILE_H 8
#define frog_adult_walk_left_WIDTH 32
#define frog_adult_walk_left_HEIGHT 32
#define frog_adult_walk_left_TILE_COUNT 23
#define frog_adult_walk_left_PALETTE_COUNT 1
#define frog_adult_walk_left_COLORS_PER_PALETTE 4
#define frog_adult_walk_left_TOTAL_COLORS 4
#define frog_adult_walk_left_PIVOT_X 16
#define frog_adult_walk_left_PIVOT_Y 16
#define frog_adult_walk_left_PIVOT_W 32
#define frog_adult_walk_left_PIVOT_H 32

BANKREF_EXTERN(frog_adult_walk_left)

extern const palette_color_t frog_adult_walk_left_palettes[4];
extern const uint8_t frog_adult_walk_left_tiles[368];

extern const metasprite_t* const frog_adult_walk_left_metasprites[2];

#endif
