//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dirt_H
#define METASPRITE_dirt_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dirt_TILE_ORIGIN 0
#define dirt_TILE_W 8
#define dirt_TILE_H 8
#define dirt_WIDTH 8
#define dirt_HEIGHT 8
#define dirt_TILE_COUNT 4
#define dirt_PALETTE_COUNT 1
#define dirt_COLORS_PER_PALETTE 4
#define dirt_TOTAL_COLORS 4
#define dirt_PIVOT_X 4
#define dirt_PIVOT_Y 4
#define dirt_PIVOT_W 8
#define dirt_PIVOT_H 8

BANKREF_EXTERN(dirt)

extern const palette_color_t dirt_palettes[4];
extern const uint8_t dirt_tiles[64];

extern const metasprite_t* const dirt_metasprites[4];

#endif
