//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_emote_sleep_H
#define METASPRITE_emote_sleep_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define emote_sleep_TILE_ORIGIN 0
#define emote_sleep_TILE_W 8
#define emote_sleep_TILE_H 8
#define emote_sleep_WIDTH 8
#define emote_sleep_HEIGHT 8
#define emote_sleep_TILE_COUNT 2
#define emote_sleep_PALETTE_COUNT 1
#define emote_sleep_COLORS_PER_PALETTE 4
#define emote_sleep_TOTAL_COLORS 4
#define emote_sleep_PIVOT_X 4
#define emote_sleep_PIVOT_Y 4
#define emote_sleep_PIVOT_W 8
#define emote_sleep_PIVOT_H 8

BANKREF_EXTERN(emote_sleep)

extern const palette_color_t emote_sleep_palettes[4];
extern const uint8_t emote_sleep_tiles[32];

extern const metasprite_t* const emote_sleep_metasprites[2];

#endif
