//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_emote_hungry_H
#define METASPRITE_emote_hungry_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define emote_hungry_TILE_ORIGIN 0
#define emote_hungry_TILE_W 8
#define emote_hungry_TILE_H 8
#define emote_hungry_WIDTH 8
#define emote_hungry_HEIGHT 8
#define emote_hungry_TILE_COUNT 2
#define emote_hungry_PALETTE_COUNT 1
#define emote_hungry_COLORS_PER_PALETTE 4
#define emote_hungry_TOTAL_COLORS 4
#define emote_hungry_PIVOT_X 4
#define emote_hungry_PIVOT_Y 4
#define emote_hungry_PIVOT_W 8
#define emote_hungry_PIVOT_H 8

BANKREF_EXTERN(emote_hungry)

extern const palette_color_t emote_hungry_palettes[4];
extern const uint8_t emote_hungry_tiles[32];

extern const metasprite_t* const emote_hungry_metasprites[2];

#endif
