#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(emote_sleep)

const palette_color_t emote_sleep_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8(176,184,127), RGB8( 68, 68, 41)
	
};

const uint8_t emote_sleep_tiles[32] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x7c,0x00,
	0x7c,0x38,0x38,0x10,
	0x7c,0x38,0x7c,0x00,
	
0x00,0x00,0xfc,0x00,
	0xfc,0x78,0x78,0x10,
	0x78,0x20,0xfc,0x78,
	0xfc,0x00,0x00,0x00
	
};

const metasprite_t emote_sleep_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, 0), METASPR_TERM
};

const metasprite_t emote_sleep_metasprite1[] = {
	METASPR_ITEM(0, 0, 1, 0), METASPR_TERM
};

const metasprite_t* const emote_sleep_metasprites[2] = {
	emote_sleep_metasprite0, emote_sleep_metasprite1
};
