//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_emote_happy_H
#define METASPRITE_emote_happy_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define emote_happy_TILE_ORIGIN 0
#define emote_happy_TILE_W 8
#define emote_happy_TILE_H 8
#define emote_happy_WIDTH 8
#define emote_happy_HEIGHT 8
#define emote_happy_TILE_COUNT 2
#define emote_happy_PALETTE_COUNT 1
#define emote_happy_COLORS_PER_PALETTE 4
#define emote_happy_TOTAL_COLORS 4
#define emote_happy_PIVOT_X 4
#define emote_happy_PIVOT_Y 4
#define emote_happy_PIVOT_W 8
#define emote_happy_PIVOT_H 8

BANKREF_EXTERN(emote_happy)

extern const palette_color_t emote_happy_palettes[4];
extern const uint8_t emote_happy_tiles[32];

extern const metasprite_t* const emote_happy_metasprites[2];

#endif
