//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_emote_tired_H
#define METASPRITE_emote_tired_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define emote_tired_TILE_ORIGIN 0
#define emote_tired_TILE_W 8
#define emote_tired_TILE_H 8
#define emote_tired_WIDTH 8
#define emote_tired_HEIGHT 8
#define emote_tired_TILE_COUNT 2
#define emote_tired_PALETTE_COUNT 1
#define emote_tired_COLORS_PER_PALETTE 4
#define emote_tired_TOTAL_COLORS 4
#define emote_tired_PIVOT_X 4
#define emote_tired_PIVOT_Y 4
#define emote_tired_PIVOT_W 8
#define emote_tired_PIVOT_H 8

BANKREF_EXTERN(emote_tired)

extern const palette_color_t emote_tired_palettes[4];
extern const uint8_t emote_tired_tiles[32];

extern const metasprite_t* const emote_tired_metasprites[2];

#endif
