#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(emote_dirty)

const palette_color_t emote_dirty_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8(176,184,127), RGB8( 68, 68, 41)
	
};

const uint8_t emote_dirty_tiles[32] = {
	0x00,0x00,0x00,0x00,
	0x60,0x40,0x3c,0x28,
	0x36,0x24,0x6c,0x48,
	0x66,0x44,0x30,0x20,
	
0x00,0x00,0x0c,0x08,
	0x06,0x04,0x66,0x44,
	0x3c,0x28,0x6c,0x48,
	0x36,0x24,0x00,0x00
	
};

const metasprite_t emote_dirty_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

const metasprite_t emote_dirty_metasprite1[] = {
	METASPR_ITEM(-4, -4, 1, 0), METASPR_TERM
};

const metasprite_t* const emote_dirty_metasprites[2] = {
	emote_dirty_metasprite0, emote_dirty_metasprite1
};
