//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_emote_dirty_H
#define METASPRITE_emote_dirty_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define emote_dirty_TILE_ORIGIN 0
#define emote_dirty_TILE_W 8
#define emote_dirty_TILE_H 8
#define emote_dirty_WIDTH 8
#define emote_dirty_HEIGHT 8
#define emote_dirty_TILE_COUNT 2
#define emote_dirty_PALETTE_COUNT 1
#define emote_dirty_COLORS_PER_PALETTE 4
#define emote_dirty_TOTAL_COLORS 4
#define emote_dirty_PIVOT_X 4
#define emote_dirty_PIVOT_Y 4
#define emote_dirty_PIVOT_W 8
#define emote_dirty_PIVOT_H 8

BANKREF_EXTERN(emote_dirty)

extern const palette_color_t emote_dirty_palettes[4];
extern const uint8_t emote_dirty_tiles[32];

extern const metasprite_t* const emote_dirty_metasprites[2];

#endif
