#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(emote_sad)

const palette_color_t emote_sad_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8(176,184,127), RGB8( 68, 68, 41)
	
};

const uint8_t emote_sad_tiles[32] = {
	0x1e,0x14,0x7e,0x54,
	0x7e,0x50,0x78,0x10,
	0x18,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	
0x00,0x00,0x7e,0x54,
	0x7e,0x50,0x78,0x50,
	0x78,0x10,0x18,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t emote_sad_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

const metasprite_t emote_sad_metasprite1[] = {
	METASPR_ITEM(-4, -4, 1, 0), METASPR_TERM
};

const metasprite_t* const emote_sad_metasprites[2] = {
	emote_sad_metasprite0, emote_sad_metasprite1
};
