//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_emote_sad_H
#define METASPRITE_emote_sad_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define emote_sad_TILE_ORIGIN 0
#define emote_sad_TILE_W 8
#define emote_sad_TILE_H 8
#define emote_sad_WIDTH 8
#define emote_sad_HEIGHT 8
#define emote_sad_TILE_COUNT 2
#define emote_sad_PALETTE_COUNT 1
#define emote_sad_COLORS_PER_PALETTE 4
#define emote_sad_TOTAL_COLORS 4
#define emote_sad_PIVOT_X 0
#define emote_sad_PIVOT_Y 0
#define emote_sad_PIVOT_W 8
#define emote_sad_PIVOT_H 8

BANKREF_EXTERN(emote_sad)

extern const palette_color_t emote_sad_palettes[4];
extern const uint8_t emote_sad_tiles[32];

extern const metasprite_t* const emote_sad_metasprites[2];

#endif
