#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(emote_tired)

const palette_color_t emote_tired_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8(176,184,127), RGB8( 68, 68, 41)
	
};

const uint8_t emote_tired_tiles[32] = {
	0x70,0x00,0xf8,0x20,
	0xf8,0x50,0xf8,0x20,
	0x7c,0x08,0x08,0x00,
	0x00,0x00,0x00,0x00,
	
0x00,0x00,0x20,0x00,
	0x7c,0x20,0x3e,0x08,
	0x3e,0x14,0x3e,0x08,
	0x1c,0x00,0x00,0x00
	
};

const metasprite_t emote_tired_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

const metasprite_t emote_tired_metasprite1[] = {
	METASPR_ITEM(-4, -4, 1, 0), METASPR_TERM
};

const metasprite_t* const emote_tired_metasprites[2] = {
	emote_tired_metasprite0, emote_tired_metasprite1
};
