//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fly_H
#define METASPRITE_fly_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fly_TILE_ORIGIN 0
#define fly_TILE_W 8
#define fly_TILE_H 8
#define fly_WIDTH 8
#define fly_HEIGHT 8
#define fly_TILE_COUNT 2
#define fly_PALETTE_COUNT 1
#define fly_COLORS_PER_PALETTE 4
#define fly_TOTAL_COLORS 4
#define fly_PIVOT_X 0
#define fly_PIVOT_Y 0
#define fly_PIVOT_W 8
#define fly_PIVOT_H 8

BANKREF_EXTERN(fly)

extern const palette_color_t fly_palettes[4];
extern const uint8_t fly_tiles[32];

extern const metasprite_t* const fly_metasprites[2];

#endif
