#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(fly)

const palette_color_t fly_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8(176,184,127), RGB8( 68, 68, 41)
	
};

const uint8_t fly_tiles[32] = {
	0x66,0x66,0xff,0x99,
	0xcb,0xbd,0x7e,0x7e,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	
0x00,0x00,0x7e,0x7e,
	0xcb,0xbd,0xff,0x99,
	0x66,0x66,0x00,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t fly_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t fly_metasprite1[] = {
	METASPR_ITEM(0, 0, 1, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const fly_metasprites[2] = {
	fly_metasprite0, fly_metasprite1
};
