#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(moon_sleep)

const palette_color_t moon_sleep_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(226,223,177), RGB8(176,184,127), RGB8( 68, 68, 41)
	
};

const uint8_t moon_sleep_tiles[32] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x3e,0x00,
	0x3e,0x1c,0x1c,0x08,
	0x3e,0x1c,0x3e,0x00,
	
0x00,0x00,0x3f,0x00,
	0x3f,0x1e,0x1e,0x04,
	0x1e,0x08,0x3f,0x1e,
	0x3f,0x00,0x00,0x00
	
};

const metasprite_t moon_sleep_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

const metasprite_t moon_sleep_metasprite1[] = {
	METASPR_ITEM(-4, -4, 1, 0), METASPR_TERM
};

const metasprite_t* const moon_sleep_metasprites[2] = {
	moon_sleep_metasprite0, moon_sleep_metasprite1
};
