//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_moon_sleep_H
#define METASPRITE_moon_sleep_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define moon_sleep_TILE_ORIGIN 0
#define moon_sleep_TILE_W 8
#define moon_sleep_TILE_H 8
#define moon_sleep_WIDTH 8
#define moon_sleep_HEIGHT 8
#define moon_sleep_TILE_COUNT 2
#define moon_sleep_PALETTE_COUNT 1
#define moon_sleep_COLORS_PER_PALETTE 4
#define moon_sleep_TOTAL_COLORS 4
#define moon_sleep_PIVOT_X 4
#define moon_sleep_PIVOT_Y 4
#define moon_sleep_PIVOT_W 8
#define moon_sleep_PIVOT_H 8

BANKREF_EXTERN(moon_sleep)

extern const palette_color_t moon_sleep_palettes[4];
extern const uint8_t moon_sleep_tiles[32];

extern const metasprite_t* const moon_sleep_metasprites[2];

#endif
