//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_baby_happy_H
#define METASPRITE_frog_baby_happy_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_baby_happy_TILE_ORIGIN 0
#define frog_baby_happy_TILE_W 8
#define frog_baby_happy_TILE_H 8
#define frog_baby_happy_WIDTH 32
#define frog_baby_happy_HEIGHT 32
#define frog_baby_happy_TILE_COUNT 11
#define frog_baby_happy_PALETTE_COUNT 1
#define frog_baby_happy_COLORS_PER_PALETTE 4
#define frog_baby_happy_TOTAL_COLORS 4
#define frog_baby_happy_PIVOT_X 16
#define frog_baby_happy_PIVOT_Y 16
#define frog_baby_happy_PIVOT_W 32
#define frog_baby_happy_PIVOT_H 32

BANKREF_EXTERN(frog_baby_happy)

extern const palette_color_t frog_baby_happy_palettes[4];
extern const uint8_t frog_baby_happy_tiles[176];

extern const metasprite_t* const frog_baby_happy_metasprites[2];

#endif
