//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_baby_sad_H
#define METASPRITE_frog_baby_sad_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_baby_sad_TILE_ORIGIN 0
#define frog_baby_sad_TILE_W 8
#define frog_baby_sad_TILE_H 8
#define frog_baby_sad_WIDTH 32
#define frog_baby_sad_HEIGHT 32
#define frog_baby_sad_TILE_COUNT 9
#define frog_baby_sad_PALETTE_COUNT 1
#define frog_baby_sad_COLORS_PER_PALETTE 4
#define frog_baby_sad_TOTAL_COLORS 4
#define frog_baby_sad_PIVOT_X 16
#define frog_baby_sad_PIVOT_Y 16
#define frog_baby_sad_PIVOT_W 32
#define frog_baby_sad_PIVOT_H 32

BANKREF_EXTERN(frog_baby_sad)

extern const palette_color_t frog_baby_sad_palettes[4];
extern const uint8_t frog_baby_sad_tiles[144];

extern const metasprite_t* const frog_baby_sad_metasprites[2];

#endif
