//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_baby_H
#define METASPRITE_frog_baby_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_baby_TILE_ORIGIN 0
#define frog_baby_TILE_W 8
#define frog_baby_TILE_H 8
#define frog_baby_WIDTH 32
#define frog_baby_HEIGHT 32
#define frog_baby_TILE_COUNT 119
#define frog_baby_PALETTE_COUNT 1
#define frog_baby_COLORS_PER_PALETTE 4
#define frog_baby_TOTAL_COLORS 4
#define frog_baby_PIVOT_X 16
#define frog_baby_PIVOT_Y 16
#define frog_baby_PIVOT_W 32
#define frog_baby_PIVOT_H 32

BANKREF_EXTERN(frog_baby)

extern const palette_color_t frog_baby_palettes[4];
extern const uint8_t frog_baby_tiles[1904];

extern const metasprite_t* const frog_baby_metasprites[25];

#endif
