//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_axolotl_H
#define METASPRITE_frog_axolotl_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_axolotl_TILE_ORIGIN 0
#define frog_axolotl_TILE_W 8
#define frog_axolotl_TILE_H 8
#define frog_axolotl_WIDTH 32
#define frog_axolotl_HEIGHT 32
#define frog_axolotl_TILE_COUNT 190
#define frog_axolotl_PALETTE_COUNT 1
#define frog_axolotl_COLORS_PER_PALETTE 4
#define frog_axolotl_TOTAL_COLORS 4
#define frog_axolotl_PIVOT_X 16
#define frog_axolotl_PIVOT_Y 16
#define frog_axolotl_PIVOT_W 32
#define frog_axolotl_PIVOT_H 32

BANKREF_EXTERN(frog_axolotl)

extern const palette_color_t frog_axolotl_palettes[4];
extern const uint8_t frog_axolotl_tiles[3040];

extern const metasprite_t* const frog_axolotl_metasprites[25];

#endif
