//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_teen_tail_H
#define METASPRITE_frog_teen_tail_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_teen_tail_TILE_ORIGIN 0
#define frog_teen_tail_TILE_W 8
#define frog_teen_tail_TILE_H 8
#define frog_teen_tail_WIDTH 32
#define frog_teen_tail_HEIGHT 32
#define frog_teen_tail_TILE_COUNT 129
#define frog_teen_tail_PALETTE_COUNT 1
#define frog_teen_tail_COLORS_PER_PALETTE 4
#define frog_teen_tail_TOTAL_COLORS 4
#define frog_teen_tail_PIVOT_X 16
#define frog_teen_tail_PIVOT_Y 16
#define frog_teen_tail_PIVOT_W 32
#define frog_teen_tail_PIVOT_H 32

BANKREF_EXTERN(frog_teen_tail)

extern const palette_color_t frog_teen_tail_palettes[4];
extern const uint8_t frog_teen_tail_tiles[2064];

extern const metasprite_t* const frog_teen_tail_metasprites[25];

#endif
