//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_egg_H
#define METASPRITE_frog_egg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_egg_TILE_ORIGIN 0
#define frog_egg_TILE_W 8
#define frog_egg_TILE_H 8
#define frog_egg_WIDTH 32
#define frog_egg_HEIGHT 32
#define frog_egg_TILE_COUNT 4
#define frog_egg_PALETTE_COUNT 1
#define frog_egg_COLORS_PER_PALETTE 4
#define frog_egg_TOTAL_COLORS 4
#define frog_egg_PIVOT_X 16
#define frog_egg_PIVOT_Y 16
#define frog_egg_PIVOT_W 32
#define frog_egg_PIVOT_H 32

BANKREF_EXTERN(frog_egg)

extern const palette_color_t frog_egg_palettes[4];
extern const uint8_t frog_egg_tiles[64];

extern const metasprite_t* const frog_egg_metasprites[2];

#endif
