//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_teen_tail_wash_H
#define METASPRITE_frog_teen_tail_wash_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_teen_tail_wash_TILE_ORIGIN 0
#define frog_teen_tail_wash_TILE_W 8
#define frog_teen_tail_wash_TILE_H 8
#define frog_teen_tail_wash_WIDTH 32
#define frog_teen_tail_wash_HEIGHT 32
#define frog_teen_tail_wash_TILE_COUNT 21
#define frog_teen_tail_wash_PALETTE_COUNT 1
#define frog_teen_tail_wash_COLORS_PER_PALETTE 4
#define frog_teen_tail_wash_TOTAL_COLORS 4
#define frog_teen_tail_wash_PIVOT_X 16
#define frog_teen_tail_wash_PIVOT_Y 16
#define frog_teen_tail_wash_PIVOT_W 32
#define frog_teen_tail_wash_PIVOT_H 32

BANKREF_EXTERN(frog_teen_tail_wash)

extern const palette_color_t frog_teen_tail_wash_palettes[4];
extern const uint8_t frog_teen_tail_wash_tiles[336];

extern const metasprite_t* const frog_teen_tail_wash_metasprites[2];

#endif
