//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_mush_stand_H
#define METASPRITE_frog_mush_stand_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_mush_stand_TILE_ORIGIN 0
#define frog_mush_stand_TILE_W 8
#define frog_mush_stand_TILE_H 8
#define frog_mush_stand_WIDTH 32
#define frog_mush_stand_HEIGHT 32
#define frog_mush_stand_TILE_COUNT 16
#define frog_mush_stand_PALETTE_COUNT 1
#define frog_mush_stand_COLORS_PER_PALETTE 4
#define frog_mush_stand_TOTAL_COLORS 4
#define frog_mush_stand_PIVOT_X 16
#define frog_mush_stand_PIVOT_Y 16
#define frog_mush_stand_PIVOT_W 32
#define frog_mush_stand_PIVOT_H 32

BANKREF_EXTERN(frog_mush_stand)

extern const palette_color_t frog_mush_stand_palettes[4];
extern const uint8_t frog_mush_stand_tiles[256];

extern const metasprite_t* const frog_mush_stand_metasprites[2];

#endif
