//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_teen_apple_H
#define METASPRITE_frog_teen_apple_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_teen_apple_TILE_ORIGIN 0
#define frog_teen_apple_TILE_W 8
#define frog_teen_apple_TILE_H 8
#define frog_teen_apple_WIDTH 32
#define frog_teen_apple_HEIGHT 32
#define frog_teen_apple_TILE_COUNT 132
#define frog_teen_apple_PALETTE_COUNT 1
#define frog_teen_apple_COLORS_PER_PALETTE 4
#define frog_teen_apple_TOTAL_COLORS 4
#define frog_teen_apple_PIVOT_X 16
#define frog_teen_apple_PIVOT_Y 16
#define frog_teen_apple_PIVOT_W 32
#define frog_teen_apple_PIVOT_H 32

BANKREF_EXTERN(frog_teen_apple)

extern const palette_color_t frog_teen_apple_palettes[4];
extern const uint8_t frog_teen_apple_tiles[2112];

extern const metasprite_t* const frog_teen_apple_metasprites[25];

#endif
