//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_child_H
#define METASPRITE_frog_child_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_child_TILE_ORIGIN 0
#define frog_child_TILE_W 8
#define frog_child_TILE_H 8
#define frog_child_WIDTH 32
#define frog_child_HEIGHT 32
#define frog_child_TILE_COUNT 107
#define frog_child_PALETTE_COUNT 1
#define frog_child_COLORS_PER_PALETTE 4
#define frog_child_TOTAL_COLORS 4
#define frog_child_PIVOT_X 16
#define frog_child_PIVOT_Y 16
#define frog_child_PIVOT_W 32
#define frog_child_PIVOT_H 32

BANKREF_EXTERN(frog_child)

extern const palette_color_t frog_child_palettes[4];
extern const uint8_t frog_child_tiles[1712];

extern const metasprite_t* const frog_child_metasprites[25];

#endif
