//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_dragon_H
#define METASPRITE_frog_dragon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_dragon_TILE_ORIGIN 0
#define frog_dragon_TILE_W 8
#define frog_dragon_TILE_H 8
#define frog_dragon_WIDTH 32
#define frog_dragon_HEIGHT 32
#define frog_dragon_TILE_COUNT 194
#define frog_dragon_PALETTE_COUNT 1
#define frog_dragon_COLORS_PER_PALETTE 4
#define frog_dragon_TOTAL_COLORS 4
#define frog_dragon_PIVOT_X 16
#define frog_dragon_PIVOT_Y 16
#define frog_dragon_PIVOT_W 32
#define frog_dragon_PIVOT_H 32

BANKREF_EXTERN(frog_dragon)

extern const palette_color_t frog_dragon_palettes[4];
extern const uint8_t frog_dragon_tiles[3104];

extern const metasprite_t* const frog_dragon_metasprites[25];

#endif
