//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_angel_H
#define METASPRITE_frog_angel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_angel_TILE_ORIGIN 0
#define frog_angel_TILE_W 8
#define frog_angel_TILE_H 8
#define frog_angel_WIDTH 24
#define frog_angel_HEIGHT 16
#define frog_angel_TILE_COUNT 8
#define frog_angel_PALETTE_COUNT 1
#define frog_angel_COLORS_PER_PALETTE 4
#define frog_angel_TOTAL_COLORS 4
#define frog_angel_PIVOT_X 12
#define frog_angel_PIVOT_Y 8
#define frog_angel_PIVOT_W 24
#define frog_angel_PIVOT_H 16

BANKREF_EXTERN(frog_angel)

extern const palette_color_t frog_angel_palettes[4];
extern const uint8_t frog_angel_tiles[128];

extern const metasprite_t* const frog_angel_metasprites[2];

#endif
