//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frog_dino_tickled_H
#define METASPRITE_frog_dino_tickled_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frog_dino_tickled_TILE_ORIGIN 0
#define frog_dino_tickled_TILE_W 8
#define frog_dino_tickled_TILE_H 8
#define frog_dino_tickled_WIDTH 32
#define frog_dino_tickled_HEIGHT 32
#define frog_dino_tickled_TILE_COUNT 20
#define frog_dino_tickled_PALETTE_COUNT 1
#define frog_dino_tickled_COLORS_PER_PALETTE 4
#define frog_dino_tickled_TOTAL_COLORS 4
#define frog_dino_tickled_PIVOT_X 16
#define frog_dino_tickled_PIVOT_Y 16
#define frog_dino_tickled_PIVOT_W 32
#define frog_dino_tickled_PIVOT_H 32

BANKREF_EXTERN(frog_dino_tickled)

extern const palette_color_t frog_dino_tickled_palettes[4];
extern const uint8_t frog_dino_tickled_tiles[320];

extern const metasprite_t* const frog_dino_tickled_metasprites[2];

#endif
